title: 'Pietro Bardini'
description: "Pietro Bardini | AV Artist"

header_pages:
  - home.md
  - cv.md
  - IDMCITDHIL.md
  - CorpusAlign.md
  - AEcoSys.md
  - SL_genCore.md
  - SteelTuner.md
  - YSOSLS.md
  - Heart.md
  - Crypt.md
  - MP.md
  - Combat.md

style: light 

footer: '<a href="https://instagram.com/pietrobardini">IG</a>'

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
